### ISSUE TITLE
samples are missing index.html files

### ISSUE THREAD

**Issue by AlbyIanna** [encrypted-dev/userbase-samples#9]
In the various README, I can read that I just need to run
```
npm install
npm run build
```
then open `dist/index.html` in your browser, and the app should run. But actually no `index.html` file will be created in the `dist` folder.

**Comment by adaddeo** [comment]
Great point, these should've been included but were being filtered out by .gitignore.

Fixed in https://github.com/encrypted-dev/userbase-samples/commit/776ccfbb29014216beaacad7f7048a482cda3b85

If you pull down the current master those index.html files will be present. Thanks!
